variables:
  configuration: Release
  platform: x64

resources:
- repo: self
  fetchDepth: 1

stages:
- stage: Build
  jobs:
  - job: Build
    strategy:
      matrix:
        Windows_vc141:
          vmImage: VS2017-Win2016
          project: vs2017
          compiler: vc141
          installCommand: 'choco install python3'
          id: 'vc141_win_$(platform)_$(configuration)'
          CC: cl.exe
          CXX: cl.exe
          BUILD_DIR: vc141

        Linux_gcc9:
          vmImage: Ubuntu-18.04
          project: ninja
          compiler: gcc
          installCommand: |
            sudo dpkg --add-architecture i386
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install g++-9 ninja-build wine64 wine64-tools libwine-dev winetricks libx11-dev libgl1-mesa-dev libopenal-dev python3
            export WINEARCH=win32
            winetricks
          id: 'gcc9_linux_$(platform)_$(configuration)'
          CC: gcc-9
          CXX: g++-9
          BUILD_DIR: gcc9

        Linux_gcc10:
          vmImage: Ubuntu-18.04
          project: ninja
          compiler: gcc
          installCommand: |
            sudo dpkg --add-architecture i386
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install g++-10 ninja-build wine64 wine64-tools libwine-dev winetricks libx11-dev libgl1-mesa-dev libopenal-dev python3
            export WINEARCH=win32
            winetricks
          id: 'gcc10_linux_$(platform)_$(configuration)'
          CC: gcc-10
          CXX: g++-10
          BUILD_DIR: gcc10

        Linux_clang10:
          vmImage: Ubuntu-18.04
          project: ninja
          compiler: clang
          installCommand: |
            sudo dpkg --add-architecture i386
            wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install clang-10 libc++-10-dev libc++abi-10-dev lld-10 ninja-build wine64 wine64-tools libwine-dev winetricks libx11-dev libgl1-mesa-dev libopenal-dev python3
            export WINEARCH=win32
            winetricks
          id: 'clang10_linux_$(platform)_$(configuration)'
          CC: clang-10
          CXX: clang++-10
          BUILD_DIR: clang10

        Linux_clang11:
          vmImage: Ubuntu-18.04
          project: ninja
          compiler: clang
          installCommand: |
            sudo dpkg --add-architecture i386
            wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main"
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install clang-11 libc++-11-dev libc++abi-11-dev lld-11 ninja-build wine64 wine64-tools libwine-dev winetricks libx11-dev libgl1-mesa-dev libopenal-dev python3
            export WINEARCH=win32
            winetricks
          id: 'clang11_linux_$(platform)_$(configuration)'
          CC: clang-11
          CXX: clang++-11
          BUILD_DIR: clang11

#        macOS_10_clang:
#          vmImage: macOS 10.14
#          project: ninja
#          compiler: clang
#          installCommand: |
#            brew tap gongminmin/core
#            brew install --cask xquartz
#            brew install ninja wine
#            wine --version
#            winegcc --version
#          id: 'clang_darwin_$(platform)_$(configuration)'
#          CC: clang
#          CXX: clang++
#          BUILD_DIR: clang
#          MACOSX_DEPLOYMENT_TARGET: 10.14

    pool:
      vmImage: $(vmImage)

    steps:
      - bash: eval '$(installCommand)'
        displayName: 'Install'

      - task: Cache@2
        inputs:
          key: 'Build_External | "$(Agent.OS)" | $(id)'
          path: Build/$(BUILD_DIR)/External
        displayName: Cache Build/External

      - task: Cache@2
        inputs:
          key: 'Build_Ninja | "$(Agent.OS)" | $(id)'
          path: Build/$(BUILD_DIR)/Ninja
          cacheHitVar: CACHE_RESTORED
        displayName: Cache Build/ninja
        condition: eq(variables.project, 'ninja')

      - bash: |
          mv Build/$(BUILD_DIR)/Ninja/ninja_deps Build/$(BUILD_DIR)/.ninja_deps
          mv Build/$(BUILD_DIR)/Ninja/ninja_log Build/$(BUILD_DIR)/.ninja_log
          rmdir Build/$(BUILD_DIR)/Ninja
        displayName: 'Restore ninja files'
        condition: and(eq(variables.CACHE_RESTORED, 'true'), eq(variables.project, 'ninja'))

      - task: Cache@2
        inputs:
          key: 'External | "$(Agent.OS)"'
          path: External
        displayName: Cache External

      - task: Cache@2
        inputs:
          key: 'KlayGE_media | "$(Agent.OS)"'
          path: KlayGE/media
        displayName: Cache KlayGE/media

      - task: Cache@2
        inputs:
          key: 'KlayGE_Samples_media | "$(Agent.OS)"'
          path: KlayGE/Samples/media
        displayName: Cache KlayGE/Samples/media

      - task: Cache@2
        inputs:
          key: 'KlayGE_Tests_media | "$(Agent.OS)"'
          path: KlayGE/Tests/media
        displayName: Cache KlayGE/Tests/media

      - task: Cache@2
        inputs:
          key: 'KlayGE_Tools_media | "$(Agent.OS)"'
          path: KlayGE/Tools/media
        displayName: Cache KlayGE/Tools/media

      - task: Cache@2
        inputs:
          key: 'KlayGE_Tutorials_media | "$(Agent.OS)"'
          path: KlayGE/Tutorials/media
        displayName: Cache KlayGE/Tutorials/media

      - script: |
          git config --global user.email "dummy@example.com"
          git config --global user.name "Dummy Name"
          # Reset the repo to restore changes in External
          git reset --hard
        displayName: 'Config git'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'
  
      - task: PythonScript@0
        displayName: 'Build'
        inputs:
          scriptPath: Build.py
          arguments: '$(project) $(compiler) $(platform) $(configuration)'

      - task: PythonScript@0
        displayName: 'Generate artifacts'
        inputs:
          scriptPath: Package.py
          arguments: '$(Build.ArtifactStagingDirectory) $(project) $(compiler) $(platform) $(configuration)'
        condition: succeeded()

      - bash: 'echo $BUILD_SOURCEVERSION > $BUILD_ARTIFACTSTAGINGDIRECTORY/GIT-COMMIT.txt'
        displayName: 'Add commit info'
        condition: succeeded()

      - task: PublishPipelineArtifact@1
        displayName: 'Publish artifacts'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifactName: KlayGE_Samples_$(id)
        condition: succeeded()

      - bash: |
          mkdir Build/$(BUILD_DIR)/Ninja
          mv -f Build/$(BUILD_DIR)/.ninja_deps Build/$(BUILD_DIR)/Ninja/ninja_deps
          mv -f Build/$(BUILD_DIR)/.ninja_log Build/$(BUILD_DIR)/Ninja/ninja_log
        displayName: 'Backup ninja files'
        condition: and(succeeded(), eq(variables.project, 'ninja'))
